# -*- coding: utf-8 -*-
"""CalculadoraExercícioModulo1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h8BxPJJaSqZcICWQYOogljNf8PEy_hP_
"""

#Converter a string em int; depois em float

def converter_para_numero(s):
    try:
        return int(s)
    except ValueError:
        try:
            return float(s)
        except ValueError:
            raise ValueError(f"'{s}' não é um número válido.")

#Escolher a operação da calculadora

def escolher_operacao():
    print("\nEscolha a operação:")
    print("  1) Adição (+)")
    print("  2) Subtração (-)")
    print("  3) Multiplicação (*)")
    print("  4) Divisão (/)")
    print("  Q) Sair")
    return input("Digite o número da operação (ou Q para sair): ").strip().lower()

#Função que define o funcionamento de cada operação da calculadora

def calcular(op, a, b):
    if op == "1":
        return a + b
    if op == "2":
        return a - b
    if op == "3":
        return a * b
    if op == "4":
        if b == 0:
            raise ZeroDivisionError("Divisão por zero não permitida.")
        return a / b
    raise ValueError("Operação desconhecida.")

def main():
    print("=== Calculadora Simples ===")

    #Interação com o Menu da calculadora
    while True:
        op = escolher_operacao()
        if op == "q":
            print("Encerrando a calculadora. Até mais!")
            break

        if op not in {"1","2","3","4"}:
            print("Opção inválida — tente novamente.")
            continue

        #Coletar números para realizar a operação
        raw_a = input("Digite o primeiro número: ").strip()
        raw_b = input("Digite o segundo número: ").strip()

        #Excecutar função de conversão para número em cada input coletado
        try:
            a = converter_para_numero(raw_a)
            b = converter_para_numero(raw_b)
        except ValueError as e:
            print("Entrada inválida:", e)
            continue

        #Executar operação matemática escolhida e tratar erro de Divisão por Zero
        try:
            resultado = calcular(op, a, b)
        except ZeroDivisionError as e:
            print("Erro:", e)
            continue

        print(f"Resultado: {resultado}")

main()